
INTF := eliom_comet.cmi             \
        eliom_react.cmi             \
        eliom_bus.cmi               \
        eliom_tools.cmi             \


NO_MLI := eliom_pervasives_base.cmi

IMPL := ${PROJECTNAME}_client.cma      \
        ${PROJECTNAME}_client_main.cmo \

STUBS := dlleliom_client.so \
	 libeliom_client.a  \
	 eliom_client.js    \

NOP4 := eliom_lib.mli

DOC := ${subst .cmi,.mli, ${filter-out ${NO_MLI}, ${INTF}}} \
       eliom_types_base.mli \
       eliom_comet_base.mli \
