

val raw_a_onabort : Xml.event_handler -> [> | `OnAbort] attrib
val raw_a_onafterprint : Xml.event_handler -> [> | `OnAfterPrint] attrib
val raw_a_onbeforeprint : Xml.event_handler -> [> | `OnBeforePrint] attrib
val raw_a_onbeforeunload : Xml.event_handler -> [> | `OnBeforeUnload] attrib
val raw_a_onblur : Xml.event_handler -> [> | `OnBlur] attrib
val raw_a_oncanplay : Xml.event_handler -> [> | `OnCanPlay] attrib
val raw_a_oncanplaythrough : Xml.event_handler -> [> | `OnCanPlayThrough] attrib
val raw_a_onchange : Xml.event_handler -> [> | `OnChange] attrib
val raw_a_onclick : Xml.event_handler -> [> | `OnClick] attrib
val raw_a_oncontextmenu : Xml.event_handler -> [> | `OnContextMenu] attrib
val raw_a_ondblclick : Xml.event_handler -> [> | `OnDblClick] attrib
val raw_a_ondrag : Xml.event_handler -> [> | `OnDrag] attrib
val raw_a_ondragend : Xml.event_handler -> [> | `OnDragEnd] attrib
val raw_a_ondragenter : Xml.event_handler -> [> | `OnDragEnter] attrib
val raw_a_ondragleave : Xml.event_handler -> [> | `OnDragLeave] attrib
val raw_a_ondragover : Xml.event_handler -> [> | `OnDragOver] attrib
val raw_a_ondragstart : Xml.event_handler -> [> | `OnDragStart] attrib
val raw_a_ondrop : Xml.event_handler -> [> | `OnDrop] attrib
val raw_a_ondurationchange : Xml.event_handler -> [> | `OnDurationChange] attrib
val raw_a_onemptied : Xml.event_handler -> [> | `OnEmptied] attrib
val raw_a_onended : Xml.event_handler -> [> | `OnEnded] attrib
val raw_a_onerror : Xml.event_handler -> [> | `OnError] attrib
val raw_a_onfocus : Xml.event_handler -> [> | `OnFocus] attrib
val raw_a_onformchange : Xml.event_handler -> [> | `OnFormChange] attrib
val raw_a_onforminput : Xml.event_handler -> [> | `OnFormInput] attrib
val raw_a_onhashchange : Xml.event_handler -> [> | `OnHashChange] attrib
val raw_a_oninput : Xml.event_handler -> [> | `OnInput] attrib
val raw_a_oninvalid : Xml.event_handler -> [> | `OnInvalid] attrib
val raw_a_onmousedown : Xml.event_handler -> [> | `OnMouseDown] attrib
val raw_a_onmouseup : Xml.event_handler -> [> | `OnMouseUp] attrib
val raw_a_onmouseover : Xml.event_handler -> [> | `OnMouseOver] attrib
val raw_a_onmousemove : Xml.event_handler -> [> | `OnMouseMove] attrib
val raw_a_onmouseout : Xml.event_handler -> [> | `OnMouseOut] attrib
val raw_a_onmousewheel : Xml.event_handler -> [> | `OnMouseWheel] attrib
val raw_a_onoffline : Xml.event_handler -> [> | `OnOffLine] attrib
val raw_a_ononline : Xml.event_handler -> [> | `OnOnLine] attrib
val raw_a_onpause : Xml.event_handler -> [> | `OnPause] attrib
val raw_a_onplay : Xml.event_handler -> [> | `OnPlay] attrib
val raw_a_onplaying : Xml.event_handler -> [> | `OnPlaying] attrib
val raw_a_onpagehide : Xml.event_handler -> [> | `OnPageHide] attrib
val raw_a_onpageshow : Xml.event_handler -> [> | `OnPageShow] attrib
val raw_a_onpopstate : Xml.event_handler -> [> | `OnPopState] attrib
val raw_a_onprogress : Xml.event_handler -> [> | `OnProgress] attrib
val raw_a_onratechange : Xml.event_handler -> [> | `OnRateChange] attrib
val raw_a_onreadystatechange : Xml.event_handler -> [> | `OnReadyStateChange] attrib
val raw_a_onredo : Xml.event_handler -> [> | `OnRedo] attrib
val raw_a_onresize : Xml.event_handler -> [> | `OnResize] attrib
val raw_a_onscroll : Xml.event_handler -> [> | `OnScroll] attrib
val raw_a_onseeked : Xml.event_handler -> [> | `OnSeeked] attrib
val raw_a_onseeking : Xml.event_handler -> [> | `OnSeeking] attrib
val raw_a_onselect : Xml.event_handler -> [> | `OnSelect] attrib
val raw_a_onshow : Xml.event_handler -> [> | `OnShow] attrib
val raw_a_onstalled : Xml.event_handler -> [> | `OnStalled] attrib
val raw_a_onstorage : Xml.event_handler -> [> | `OnStorage] attrib
val raw_a_onsubmit : Xml.event_handler -> [> | `OnSubmit] attrib
val raw_a_onsuspend : Xml.event_handler -> [> | `OnSuspend] attrib
val raw_a_ontimeupdate : Xml.event_handler -> [> | `OnTimeUpdate] attrib
val raw_a_onundo : Xml.event_handler -> [> | `OnUndo] attrib
val raw_a_onunload : Xml.event_handler -> [> | `OnUnload] attrib
val raw_a_onvolumechange : Xml.event_handler -> [> | `OnVolumeChange] attrib
val raw_a_onwaiting : Xml.event_handler -> [> | `OnWaiting] attrib
val raw_a_onkeypress : Xml.event_handler -> [> | `OnKeyPress] attrib
val raw_a_onkeydown : Xml.event_handler -> [> | `OnKeyDown] attrib
val raw_a_onkeyup : Xml.event_handler -> [> | `OnKeyUp] attrib
val raw_a_onload : Xml.event_handler -> [> | `OnLoad] attrib
val raw_a_onloadeddata : Xml.event_handler -> [> | `OnLoadedData] attrib
val raw_a_onloadedmetadata : Xml.event_handler -> [> | `OnLoadedMetaData] attrib
val raw_a_onloadstart : Xml.event_handler -> [> | `OnLoadStart] attrib
val raw_a_onmessage : Xml.event_handler -> [> | `OnMessage] attrib
