type event
type mouseEvent
type keyboardEvent

val a_onabort : event -> [> | `OnAbort] attrib
val a_onafterprint : event -> [> | `OnAfterPrint] attrib
val a_onbeforeprint : event -> [> | `OnBeforePrint] attrib
val a_onbeforeunload : event -> [> | `OnBeforeUnload] attrib
val a_onblur : event -> [> | `OnBlur] attrib
val a_oncanplay : event -> [> | `OnCanPlay] attrib
val a_oncanplaythrough : event -> [> | `OnCanPlayThrough] attrib
val a_onchange : event -> [> | `OnChange] attrib
val a_onclick : mouseEvent -> [> | `OnClick] attrib
val a_oncontextmenu : mouseEvent -> [> | `OnContextMenu] attrib
val a_ondblclick : mouseEvent -> [> | `OnDblClick] attrib
val a_ondrag : mouseEvent -> [> | `OnDrag] attrib
val a_ondragend : mouseEvent -> [> | `OnDragEnd] attrib
val a_ondragenter : mouseEvent -> [> | `OnDragEnter] attrib
val a_ondragleave : mouseEvent -> [> | `OnDragLeave] attrib
val a_ondragover : mouseEvent -> [> | `OnDragOver] attrib
val a_ondragstart : mouseEvent -> [> | `OnDragStart] attrib
val a_ondrop : mouseEvent -> [> | `OnDrop] attrib
val a_ondurationchange : event -> [> | `OnDurationChange] attrib
val a_onemptied : event -> [> | `OnEmptied] attrib
val a_onended : event -> [> | `OnEnded] attrib
val a_onerror : event -> [> | `OnError] attrib
val a_onfocus : event -> [> | `OnFocus] attrib
val a_onformchange : event -> [> | `OnFormChange] attrib
val a_onforminput : event -> [> | `OnFormInput] attrib
val a_onhashchange : event -> [> | `OnHashChange] attrib
val a_oninput : event -> [> | `OnInput] attrib
val a_oninvalid : event -> [> | `OnInvalid] attrib
val a_onmousedown : mouseEvent -> [> | `OnMouseDown] attrib
val a_onmouseup : mouseEvent -> [> | `OnMouseUp] attrib
val a_onmouseover : mouseEvent -> [> | `OnMouseOver] attrib
val a_onmousemove : mouseEvent -> [> | `OnMouseMove] attrib
val a_onmouseout : mouseEvent -> [> | `OnMouseOut] attrib
val a_onmousewheel : event -> [> | `OnMouseWheel] attrib
val a_onoffline : event -> [> | `OnOffLine] attrib
val a_ononline : event -> [> | `OnOnLine] attrib
val a_onpause : event -> [> | `OnPause] attrib
val a_onplay : event -> [> | `OnPlay] attrib
val a_onplaying : event -> [> | `OnPlaying] attrib
val a_onpagehide : event -> [> | `OnPageHide] attrib
val a_onpageshow : event -> [> | `OnPageShow] attrib
val a_onpopstate : event -> [> | `OnPopState] attrib
val a_onprogress : event -> [> | `OnProgress] attrib
val a_onratechange : event -> [> | `OnRateChange] attrib
val a_onreadystatechange : event -> [> | `OnReadyStateChange] attrib
val a_onredo : event -> [> | `OnRedo] attrib
val a_onresize : event -> [> | `OnResize] attrib
val a_onscroll : event -> [> | `OnScroll] attrib
val a_onseeked : event -> [> | `OnSeeked] attrib
val a_onseeking : event -> [> | `OnSeeking] attrib
val a_onselect : event -> [> | `OnSelect] attrib
val a_onshow : event -> [> | `OnShow] attrib
val a_onstalled : event -> [> | `OnStalled] attrib
val a_onstorage : event -> [> | `OnStorage] attrib
val a_onsubmit : event -> [> | `OnSubmit] attrib
val a_onsuspend : event -> [> | `OnSuspend] attrib
val a_ontimeupdate : event -> [> | `OnTimeUpdate] attrib
val a_onundo : event -> [> | `OnUndo] attrib
val a_onunload : event -> [> | `OnUnload] attrib
val a_onvolumechange : event -> [> | `OnVolumeChange] attrib
val a_onwaiting : event -> [> | `OnWaiting] attrib
val a_onkeypress : keyboardEvent -> [> | `OnKeyPress] attrib
val a_onkeydown : keyboardEvent -> [> | `OnKeyDown] attrib
val a_onkeyup : keyboardEvent -> [> | `OnKeyUp] attrib
val a_onload : event -> [> | `OnLoad] attrib
val a_onloadeddata : event -> [> | `OnLoadedData] attrib
val a_onloadedmetadata : event -> [> | `OnLoadedMetaData] attrib
val a_onloadstart : event -> [> | `OnLoadStart] attrib
val a_onmessage : event -> [> | `OnMessage] attrib
