# Which ocamlfind/camlp4/... version to use? 
# ocamlfind will choose automatically the compiler.
OCAMLFIND=ocamlfind
CAMLP4=camlp4
CAMLLEX=ocamllex
CAMLYACC=ocamlyacc
CAMLCNAME=ocamlc
# CAMLCNAME=ocamlcp -p a # No: profiling is incompatible with the -pp option

# Do you want the ocamlduce extension? (YES/NO) 
# (You need ocamlduce to be installed)
OCAMLDUCE=YES
# If you have OCamlduce installed, which ocamlducefind do you want?
OCAMLDUCEFIND=ocamlducefind

# The directory for ocsigen server (binary):
BINDIR = /usr/local/bin

# The directory for ocsigen manpage:
MANDIR = /usr/local/share/man/man1/

# Where to install the directory for ocsigen modules:
MODULEINSTALLDIR = `$(OCAMLFIND) printconf destdir`

# Where to install examples:
EXAMPLESINSTALLDIR = /usr/local/lib/ocsigen

# User who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This user must exist on your system)
OCSIGENUSER=www-data

# group who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This group must exist)
OCSIGENGROUP=www-data

# The name of the server (and the directory for the modules)
OCSIGENNAME=ocsigen

# ocsigen's logs:
LOGDIR = /var/log/$(OCSIGENNAME)

# Config files:
CONFIGDIR = /etc/$(OCSIGENNAME)

# Where to put static pages:
STATICPAGESDIR = /var/www/$(OCSIGENNAME)

# Default directory for file upload:
UPLOADDIR = /tmp

# Where to put Ocsigen documentation:
DOCDIR = /usr/share/doc/$(OCSIGENNAME)

# Do you want debugging information? (-g -dtypes)
DEBUG=NO





# If you are using ocamlnet 1, write NO here
NEWOCAMLNET=YES

# Profiling (always put NO here - but if you want to debug ocsigen):
PROFILING=NO
