# Do you want Ocsimore? (start with NO, it is easier)
OCSIMORE=YES

# The directory for ocsigen server (binary):
BINDIR = /usr/local/bin

# Where to install modules:
MODULEINSTALLDIR = `ocamlfind printconf destdir`

# User who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This user must exist on your system)
OCSIGENUSER=ocsigen

# group who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This group must exist)
OCSIGENGROUP=ocsigen

# The name of the server (and the directory for the modules)
OCSIGENNAME=ocsigen-gadt

# ocsigen's logs:
LOGDIR = /var/log/$(OCSIGENNAME)

# Config files:
CONFIGDIR = /etc/$(OCSIGENNAME)

# Where to put static pages:
STATICPAGESDIR = /var/www/$(OCSIGENNAME)

# Where to put Ocsigen documentation:
DOCDIR = /usr/share/doc/$(OCSIGENNAME)

