# Do you want Ocsimore (start with NO)?
OCSIMORE=YES

# The directory for ocsigen server (binary):
BINDIR = /usr/local/bin

# Where to install modules:
MODULEINSTALLDIR = `ocamlfind ocamlc -where`

# ocsgen's logs:
LOGDIR = /var/log/ocsigen

# Config files:
CONFIGDIR = /etc/ocsigen

# Where to put static pages:
STATICPAGESDIR = /var/www/ocsigen

# User who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This user must exist on your system)
OCSIGENUSER=ocsigen

# group who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This group must exist)
OCSIGENGROUP=ocsigen
