
BYTEDBG :=
OPTDBG  :=

ifeq "$(DEBUG)" "YES"
BYTEDBG += -g
OPTDBG  += -g
endif

ifeq "$(ANNOT)" "YES"
BYTEDBG += -dtypes
OPTDBG  += -dtypes
endif

ifeq "$(PROFILING)" "YES"
BYTEDBG :=p ${BYTEDBG}
OPTDBG  += -p
endif

SERVERDIR := ${TEMPROOT}${LIBDIR}/${PROJECTNAME}/server
CLIENTDIR := ${TEMPROOT}${LIBDIR}/${PROJECTNAME}/client
SYNTAXDIR := ${TEMPROOT}${LIBDIR}/${PROJECTNAME}/syntax

export OCAMLPATH:=${LIBDIR}:${OCAMLPATH}
