(lang dune 3.0)

(dialect
 (name "eliom-server")
 (implementation (extension "eliom"))
 (interface (extension "eliomi")))

(wrapped_executables false)

(formatting (enabled_for ocaml "eliom-server"))
