# -*- Mode: Makefile -*-

include $(DERIVING_DIR)/../Makefile.config

OCAMLDEP := ocamldep
OCAMLC := $(CAMLCNAME)
OCAMLOPT := $(CAMLOPTNAME)

TYPECONV_DIR := $(shell ${OCAMLFIND} query type-conv)
JS_OF_OCAML_DIR := ${shell ${OCAMLFIND} query js_of_ocaml}
LWT_DIR := ${shell ${OCAMLFIND} query lwt}

MODULES := Dummy         \
	   Show		\
           Eq 		\
           Bounded	\
           Enum		\
           Dump		\
           Typeable	\
           Pickle        \
	   Json          \
	   # Functor       \

##

CAMLP4O    := ${CAMLP4} -parser o -parser op -printer a
CAMLP4OF   := ${CAMLP4} -parser r -parser q -parser o -parser rp \
		        -parser op -parser g -parser m -printer a
CAMLP4ORF  := ${CAMLP4} -parser r -parser o -parser rp -parser op \
	                -parser rq -parser g -parser m -printer a
export CAMLP4O
export CAMLP4OF
export CAMLP4ORF

CAMLP4O_IS_BYTE := yes

##

ANNOTATE   := yes

##

OCAMLMAKEFILE := ${DERIVING_DIR}/OCamlMakefile
RMAKE := ${MAKE} --no-print-directory

##

# Deriving doesn't depends on hte rest of Ocsigen
LIBDIRS=
# Profiling can't be enabled with preprocessed files
PROFILING=