(* This file was generated by Eliom-distillery.
   Feel free to use it, modify it, and redistribute it as you wish. *)

let%server application_name = "%%%PROJECT_NAME%%%"
let%client application_name = Eliom.Client.get_application_name ()

(* Create a module for the application. See
   https://ocsigen.org/eliom/manual/clientserver-applications for more
   information. *)
module%shared App = Eliom.Registration.App (struct
    let application_name = application_name
    let global_data_path = Some ["__global_data__"]
  end)

(* As the headers (stylesheets, etc) won't change, we ask Eliom not to
   update the <head> of the page when changing page. (This also avoids
   blinking when changing page in iOS). *)
let%client _ = Eliom.Client.persist_document_head ()

let%server main_service =
  Eliom.Service.create ~path:(Eliom.Service.Path [])
    ~meth:(Eliom.Service.Get Eliom.Parameter.unit) ()

let%client main_service = ~%main_service

let%shared () =
  App.register ~service:main_service (fun () () ->
    Lwt.return
      Eliom.Content.Html.F.(
        html
          (head
             (title (txt "%%%PROJECT_NAME%%%"))
             [ css_link
                 ~uri:
                   (make_uri
                      ~service:(Eliom.Service.static_dir ())
                      ["css"; "%%%PROJECT_NAME%%%.css"])
                 () ])
          (body [h1 [txt "Welcome to Eliom!"]])))
