(* The test server of test.ml: pages with forms generated by Eliom, and the
   services they submit to, which answer with their parameters. *)

open Eliom
module P = Parameter
module F = Content.Html.F
module Form = F.Form

let text s = Lwt.return (s, "text/plain")

let get path params =
  Service.create ~path:(Service.Path path) ~meth:(Service.Get params) ()

let string service f = Registration.String.register ~service f

(* [page path content] registers the page [path], whose body is [content ()] *)
let page path content =
  Registration.Html.register ~service:(get [path] P.unit) (fun () () ->
    Lwt.return F.(html (head (title (txt path)) []) (body (content ()))))

let opt = Option.value ~default:"none"

(* Fields of text, a checkbox, and an optional parameter left empty *)

let simple =
  get ["simple"] P.(int "i" ** string "s" ** opt (string "o") ** bool "b")

let () =
  string simple (fun (i, (s, (o, b))) () ->
    text (Printf.sprintf "i=%d s=%s o=%s b=%b" i s (opt o) b))

let () =
  page "simple_form" (fun () ->
    [ Form.get_form ~service:simple (fun (i, (s, (o, b))) ->
        [ Form.input ~input_type:`Text ~name:i ~value:3 Form.int
        ; Form.input ~input_type:`Text ~name:s ~value:"a b&c" Form.string
        ; Form.input ~input_type:`Text ~name:o Form.string
        ; Form.bool_checkbox_one ~checked:true ~name:b () ]) ])

(* A text area, a select, radio buttons and a set of checkboxes, in a POST
   form *)

let choices =
  Service.create ~path:(Service.Path ["choices"])
    ~meth:
      (Service.Post
         ( P.unit
         , P.(string "t" ** string "sel" ** radio string "r" ** set string "c")
         ))
    ()

let () =
  string choices (fun () (t, (sel, (r, c))) ->
    text
      (Printf.sprintf "t=%s sel=%s r=%s c=%s" t sel (opt r)
         (String.concat "," (List.sort compare c))))

let () =
  page "choices_form" (fun () ->
    [ Form.post_form ~service:choices
        (fun (t, (sel, (r, c))) ->
           [ Form.textarea ~name:t ~value:"one\ntwo <&>" ()
           ; Form.select ~name:sel Form.string
               (Form.Option ([], "a", None, false))
               [Form.Option ([], "b", None, true)]
           ; Form.radio ~name:r ~value:"x" Form.string
           ; Form.radio ~checked:true ~name:r ~value:"y" Form.string
           ; Form.checkbox ~checked:true ~name:c ~value:"p" Form.string
           ; Form.checkbox ~checked:true ~name:c ~value:"q" Form.string
           ; Form.checkbox ~name:c ~value:"s" Form.string ])
        () ])

(* A list *)

let list = get ["list"] P.(list "l" (string "x"))
let () = string list (fun l () -> text (String.concat "," l))

let () =
  page "list_form" (fun () ->
    [ Form.get_form ~service:list (fun names ->
        names.P.it
          (fun name v fields ->
             Form.input ~input_type:`Text ~name ~value:v Form.string :: fields)
          ["u"; "v"; "w"] []) ])

(* Coservices *)

let fallback = get ["fallback"] P.unit
let () = string fallback (fun () () -> text "fallback")

let attached =
  Service.create_attached_post ~fallback ~post_params:P.(string "v") ()

let () = string attached (fun () v -> text ("attached " ^ v))

let na_get =
  Service.create ~path:Service.No_path ~meth:(Service.Get P.(string "v")) ()

let () = string na_get (fun v () -> text ("non-attached GET " ^ v))

let na_post =
  Service.create ~path:Service.No_path
    ~meth:(Service.Post (P.unit, P.(string "v")))
    ()

let () = string na_post (fun () v -> text ("non-attached POST " ^ v))

let csrf =
  Service.create_attached_post ~csrf_safe:true ~fallback
    ~post_params:P.(string "v")
    ()

let () = string csrf (fun () v -> text ("CSRF-safe " ^ v))
let field name = [Form.input ~input_type:`Text ~name ~value:"z" Form.string]

let () =
  page "coservice_forms" (fun () ->
    [ Form.post_form ~service:attached field ()
    ; Form.get_form ~service:na_get field
    ; Form.post_form ~service:na_post field ()
    ; Form.post_form ~service:csrf field () ])

(* A suffix *)

let suffix = get ["suffix"] P.(suffix (string "s"))
let () = string suffix (fun s () -> text ("suffix " ^ s))

let () =
  page "suffix_form" (fun () ->
    [ Form.get_form ~service:suffix (fun s ->
        [Form.input ~input_type:`Text ~name:s ~value:"a" Form.string]) ])

let () = Eliom_test_server.Server_harness.start [App.run ()]
