(* Tests of the forms generated by Eliom: submitted as a browser does, they
   send the parameters of their service. *)

open Eliom_test_server
open Lwt.Syntax

let check_response ?status ?body msg (r : Browser.response) =
  Option.iter
    (fun s -> Alcotest.(check int) (msg ^ ": status") s r.status)
    status;
  Option.iter (fun b -> Alcotest.(check string) (msg ^ ": body") b r.body) body

(* The forms of the page [url] *)
let forms b url =
  let+ r = Browser.get b url in
  check_response url ~status:200 r;
  Html_form.forms ~url r.body

let form b url =
  let+ forms = forms b url in
  match forms with
  | [form] -> form
  | _ -> Alcotest.failf "%s: %d forms" url (List.length forms)

(* [case server name f] is a test that runs [f b] with a new browser [b]. *)
let case server name f =
  Alcotest.test_case name `Quick (fun () ->
    Lwt_main.run (f (Browser.create server)))

let submitted msg expected b form =
  let+ r = Html_form.submit b form in
  check_response msg ~status:200 ~body:expected r

let fields server =
  let case = case server in
  ( "fields"
  , [ case "text and checkbox" (fun b ->
        (* An empty field of an optional parameter is the empty string. *)
        let* form = form b "/simple_form" in
        submitted "submitted" "i=3 s=a b&c o= b=true" b form)
    ; case "changed values" (fun b ->
        let* form = form b "/simple_form" in
        let form = Html_form.(form |> set "s" "é?=/" |> set "o" "given") in
        submitted "submitted" "i=3 s=é?=/ o=given b=true" b form)
    ; case "wrong type" (fun b ->
        let* form = form b "/simple_form" in
        let form =
          Html_form.set (List.hd (List.map fst form.Html_form.fields)) "x" form
        in
        let+ r = Html_form.submit b form in
        check_response "rejected" ~status:400 r)
    ; case "text area, select, radio buttons and checkboxes" (fun b ->
        let* form = form b "/choices_form" in
        Alcotest.(check bool) "POST" true (form.Html_form.meth = `POST);
        submitted "submitted" "t=one\ntwo <&> sel=b r=y c=p,q" b form)
    ; case "list" (fun b ->
        let* form = form b "/list_form" in
        submitted "submitted" "u,v,w" b form) ] )

let coservices server =
  let case = case server in
  let nth b i =
    let+ forms = forms b "/coservice_forms" in
    List.nth forms i
  in
  ( "coservices"
  , [ case "attached" (fun b ->
        let* form = nth b 0 in
        submitted "submitted" "attached z" b form)
    ; case "non-attached, GET" (fun b ->
        let* form = nth b 1 in
        submitted "submitted" "non-attached GET z" b form)
    ; case "non-attached, POST" (fun b ->
        let* form = nth b 2 in
        submitted "submitted" "non-attached POST z" b form)
    ; case "CSRF-safe" (fun b ->
        let* form = nth b 3 in
        let* () =
          submitted "other browser" "fallback" (Browser.create server) form
        in
        submitted "own browser" "CSRF-safe z" b form)
    ; case "suffix" (fun b ->
        (* The form sends the suffix as a parameter: the server redirects
           to the URL with the suffix. *)
        let* form = form b "/suffix_form" in
        let* r = Html_form.submit b form in
        check_response "redirection" ~status:307 r;
        match Browser.header r "location" with
        | Some location ->
            let+ r = Browser.get b (Uri.path (Uri.of_string location)) in
            check_response "page" ~status:200 ~body:"suffix a" r
        | None -> Alcotest.fail "no location") ] )

let () =
  Server_harness.with_server "./server.exe" (fun server ->
    Alcotest.run ~and_exit:false "eliom-server-forms"
      [fields server; coservices server])
