.TH eliom-distillery 1 2012-12-17
.SH NAME
eliom-distillery \- Scaffolding for your Eliom-projects.
.SH SYNOPSIS
.B eliom-distillery
.BI \-dir

.B eliom-distillery
.BI \-name \ name
[
.BI \-template \ <template>
] [
.BI \-target-directory \ <dir>
]
.SH DESCRIPTION
This program generates the scaffold for your Eliom application
from a template.
.P
Please refer to the generated README for more information on how to
work with the project.
.P
The manual on the web contains more information:
http://ocsigen.org/eliom/manual/workflow-distillery.
.SH OPTIONS
.TP 5
.BI \-dir
Display the directory where templates are installed.
.TP
.BI \-name \ name
The name of project to be generated. Note well, that this must be a
valid name for a compilation unit.
.TP
.BI \-template \ template
The template for the project.
.TP
.BI \-target-directory \ dir
Generated the project in directory <dir>.
.I name
is used by default.
.B eliom-distillery
will create it if it doesn't already exist.
.SH SEE ALSO
.BR eliomc (1).
.SH AUTHOR
.B eliom-distillery
is part of the Ocsigen-project, and written by
Benedikt Becker.
