NAME := $(notdir $(PWD))

UTIL_DEPENDS   = stdlib
MODULE_DEPENDS =

RUNTIME_SOURCES = \
	deriving_bi_outbuf.mli deriving_bi_outbuf.ml \
	deriving_Json_lexer.mli deriving_Json_lexer.ml \
	deriving_Json.mli deriving_Json.ml \
	deriving_Json_stdlib.mli deriving_Json_stdlib.ml

include ../Makefile.modules