include ../../Makefile.config

NAME := ocamlbuild_eliom

BYTE_TARGETS := $(NAME).cma
OPT_TARGETS := $(NAME).cmxa $(NAME).a

INTF := $(NAME).cmi

ifeq "${NATDYNLINK}" "YES"
    OPT_TARGETS += $(NAME).cmxs
endif

DOC := ${INTF:.cmi=.odoc}
