.\"                                      Hey, EMACS: -*- nroff -*-
.TH OCSIGEN 1 2006-09-14
.SH NAME
ocsigen \- web programming framework in OCaml
.SH SYNOPSIS
.B ocsigen
.RI [ options ]
.SH DESCRIPTION
.B ocsigen
is a programming framework providing a new way to create dynamic web sites. 
Its goal is to offer an alternative to Apache/PHP, based on cutting-edge 
technologies coming from research in programming languages. 
With
.BR ocsigen ,
you program in a concise and modular way, with a strong type system 
which helps you to produce valid xhtml. The server handles sessions, 
URLs, and page parameters automatically.
.SH OPTIONS
.TP
.BR \-c ,\  \-\-config
Alternate configuration file.
.TP
.BR \-d ,\  \-\-daemon
Daemon mode (detach the process). This is the default when there are more than 1 process.
.TP
.BR \-help ,\  \-\-help
Show summary of options.
.TP
.BR \-p ,\  \-\-pidfile
Specify a file where to write the PIDs of the servers.
.TP
.BR \-s ,\  \-\-silent
Silent mode (error messages go in errors.log only).
.TP
.BR \-v ,\  \-\-verbose
Verbose mode.
.TP
.B \-V ,\  \-\-veryverbose
Very verbose mode (debug).
.TP
.B \-version
Show version of program.
.SH SEE ALSO
.BR ocamlc (1).
.SH AUTHOR
ocsigen was written by Vincent Balat <vincent.balat@pps.jussieu.fr>.
.PP
This manual page was written by Samuel Mimram <smimram@debian.org>,
for the Debian project (but may be used by others).
