NAME := $(notdir $(PWD))

PACK_DEPENDS   =
UTIL_DEPENDS   =
MODULE_DEPENDS =

RUNTIME_SOURCES = \
	deriving_Show.mli deriving_Show.ml \
	deriving_Show_stdlib.mli deriving_Show_stdlib.ml


include ../Makefile.modules
