(executable
 (name server)
 (modules server)
 (libraries
  eliom.server
  ocsipersist-sqlite
  eliom_test_server
  eliom_test_client))

(test
 (name test)
 (modules test)
 (package eliom)
 (deps server.exe)
 (libraries
  eliom.server
  ocsipersist-sqlite
  eliom_test_server
  eliom_test_client
  lwt.unix
  alcotest))
