
INTF := server/eliom_pervasives.cmi        \
        server/eliom_cookies.cmi           \
        server/eliom_common.cmi            \
        server/eliom_types.cmi             \
        server/eliom_parameters.cmi        \
        server/eliom_services.cmi          \
        server/eliom_porcess.cmi           \
        server/eliom_config.cmi            \
        server/eliom_request_info.cmi      \
        server/eliom_state.cmi             \
        server/eliom_uri.cmi               \
        server/eliom_mkforms.cmi           \
        server/eliom_output.cmi            \
        server/eliom_comet.cmi             \
        server/eliom_tools_common.cmi      \
        server/eliom_tools.cmi             \
        server/eliom_react.cmi             \
        server/eliom_bus.cmi               \
	\
        server/eliom_mkreg.cmi             \
        server/eliom_error_pages.cmi       \
        server/eliom_references.cmi        \
        server/eliom_extensions.cmi        \
 	\
        server/extensions/eliom_s2s.cmi    \
        server/extensions/eliom_openid.cmi \
        server/extensions/atom_feed.cmi    \
        server/extensions/eliom_atom.cmi   \
	\
        client/eliom_client.cmi            \
        client/eliom_request.cmi           \

ifeq "$(OCAMLDUCE)" "YES"
INTF += xhtmltypes_duce.cmi  \
	xhtmlpretty_duce.cmi \
	eliom_duce.cmi       \
	eliom_duce_tools.cmi \
endif

IMPL := server/eliom.cma             \
        client/eliom_client.cma      \
        client/eliom_client_mail.cmo \

ifeq "$(OCAMLDUCE)" "YES"
IMPL += server/eliom_duce.cma
end

ifeq "$(NATIVECODE)" "YES"

NATIMPL := server/eliom.cmxa
ifeq "$(OCAMLDUCE)" "YES"
NATIMPL += server/eliom_duce.cmxa
endif

ifeq "$(NATDYNLINK)" "YES"
NATIMPL += server/eliom.cmxs
ifeq "$(OCAMLDUCE)" "YES"
NATIMPL += server/eliom_duce.cmxs
endif
endif

endif # "$(NATIVECODE)" "YES"

STUBS := client/dlleliom_client.so \
	 client/libeliom_client.a  \

DOCINCLUDESDIR=\
	baselib http xmlp4 server extensions eliom eliom/extensions \
	deriving/lib/modules/Json
