NAME := $(notdir $(PWD))

PACK_DEPENDS   =
UTIL_DEPENDS   =
MODULE_DEPENDS = Show Eq

RUNTIME_SOURCES = \
	deriving_interned.mli deriving_interned.ml \
	deriving_Typeable.mli deriving_Typeable.ml \
	deriving_dynmap.mli deriving_dynmap.ml     \

include ../Makefile.modules
