# Update ocsigen.org using Github Actions

name: Update Web site

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the wikidoc branch
  push:
    branches: [ wikidoc ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ wikidoc ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: wikidoc

      - name: Install OCaml 🐫
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11.x

      - name: Install HOW 🦔
        run: |
          opam pin add -y html_of_wiki https://github.com/ocsigen/html_of_wiki.git
          git clone --depth 1 https://github.com/ocsigen/ocsigen.github.io.git __ocsigen.github.io
          mv __ocsigen.github.io/template how_template

      - name: Generate doc ⚙️
        run: |
          export HOW_DOC=doc
          export HOW_CONFIG=how.json
          export HOW_OUT=_doc
          eval $(opam env)
          quickdop -f $HOW_DOC $HOW_OUT -t json -c $HOW_CONFIG -viu
          HOW_LATEST=$(find $HOW_DOC -maxdepth 1 -type d -not -name $HOW_DOC -not -name dev -exec basename {} \; | sort -nr | head -n 1)
          export HOW_LATEST
          ln -s $HOW_LATEST $HOW_OUT/latest
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; URL=latest/manual/overview" /></head><body></body></html>' > $HOW_OUT/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _doc # The folder the action should deploy.
